name: 琴弦第七
avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: '不务正业的老师'
# company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
# location: Earth # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
social:
  email: qinxiandiqi@foxmail.com
  github: qinxiandiqi
  twitter: qinxiandiqi
  # patreon: qinxiandiqi
  # paypal: qinxiandiqi
  rss: "" # Remove RSS
